---
- name: Setup workload
  hosts: k8n_control_plane
  tasks:
    - name: Install Helm
      block:
        - name: Download  'Helm' installation script
          ansible.builtin.get_url:
            url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            dest: /home/ubuntu/get-helm-3.sh
            mode: '0750'
        - name: Install 'Helm' with the installation script
          ansible.builtin.shell: /home/ubuntu/get-helm-3.sh
        - name: Add 'Helm' chart repo
          kubernetes.core.helm_repository:
            name: diploma-chart
            repo_url: https://olezhuravlev.github.io/diploma-chart/charts/
        - name: Update `Helm` repository cache
          kubernetes.core.helm:
            name: dummy
            namespace: kube-system
            state: absent
            update_repo_cache: true
