#---
#- name: Deploy TeamCity Server
#  hosts: tc-server
#  tasks:
#    - name: Install TeamCity server
#      docker_container:
#        name: tc-server
#        image: jetbrains/teamcity-server
#        state: started
#        ports:
#          - "8111:8111"
- name: Deploy TeamCity Agent
  hosts: tc-agent
  tasks:
    - name: Install TeamCity Agent
      block:
        - name: Create Teamcity Agent folder
          ansible.builtin.file:
            path: /home/ubuntu/teamcity_agent/conf
            state: directory
            mode: '0777'
        - name: Install TeamCity Agent
          docker_container:
            name: tc-agent
            image: jetbrains/teamcity-agent:2022.10.1-linux-sudo
            privileged: true
            state: started
            ports:
              - "9090:9090"
            volumes:
              - "/home/ubuntu/teamcity_agent/conf:/data/teamcity_agent/conf"
            env:
              SERVER_URL: "10.10.10.10:8111"
              DOCKER_IN_DOCKER: "start"

