---
- name: Setup Kubernetes Cluster
  hosts: k8n_control_plane
  tasks:
    - name: Install Web-application
      block:
        - name: Add 'Helm' chart repo
          kubernetes.core.helm_repository:
            name: diploma-chart
            repo_url: https://olezhuravlev.github.io/diploma-chart/charts/
        - name: Update `Helm` repository cache
          kubernetes.core.helm:
            name: dummy
            namespace: kube-system
            state: absent
            update_repo_cache: true
        - name: Deploy latest version of web-application
          kubernetes.core.helm:
            name: web-app
            chart_ref: diploma-chart/web-app
            release_namespace: default
            create_namespace: false
