---
apiVersion: v1
kind: Pod
metadata:
  name: minipg
  namespace: default
  labels:
    app: debug-tools
spec:
  containers:
  - name: minipg
    image: mini/postgresql
    ports:
    - name: minipg-port
      containerPort: 5432
      protocol: TCP
