---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: {{ include "ns" . }}
  labels:
    app: web-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      component: frontend
  template:
    metadata:
      labels:
        app: web-app
        component: frontend
    spec:
      containers:
      - name: diploma
        image: "{{- .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: frontend-port
          containerPort: 80
          protocol: TCP
---
# NodePort: Exposes the Service on each Node's IP at a static port.
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport-svc
  namespace: {{ include "ns" . }}
  labels:
    app: web-app
    component: frontend
spec:
  type: NodePort
  selector:
    app: web-app
    component: frontend
  ports:
  - name: frontend-nodeport
    protocol: TCP
    nodePort: {{ include "frontend-port" . }} # Port to apply from outside (to see ips - 'kubectl get nodes -o wide').
    port: 80 # Port to apply from inside (to see ips - 'kubectl get svc').
    targetPort: frontend-port # Port to map acces to (to see ips - 'kubectl get pods -o wide')
