---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-1gb
  labels:
    app: web-news
    component: dbase
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /persistentVolume1gb
  persistentVolumeReclaimPolicy: Retain