---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-8gb
  namespace: cicd
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitlab-storage
  capacity:
    storage: 8Gi
  hostPath:
    path: /postgresql-pv-8gb
  persistentVolumeReclaimPolicy: Retain
