---
apiVersion: v1
kind: Pod
metadata:
  name: teamcity-agent
  namespace: cicd
  labels:
    app: teamcity
    component: teamcity-agent
spec:
  containers:
    - name: teamcity-agent
      image: jetbrains/teamcity-agent
      ports:
        - containerPort: 9090
          protocol: TCP
      env:
        - name: SERVER_URL
          value: "teamcity-server-svc.cicd.svc.cluster.local:8111"
        - name: DOCKER_IN_DOCKER
          value: start
      securityContext:
        privileged: true
        runAsUser: 0
