apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: teamcity-agent-role
  namespace: cicd
  labels:
    app: teamcity
    component: teamcity-agent
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "list", "get" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "create", "list", "delete" ]
  - apiGroups: [ "extensions", "apps" ]
    resources: [ "deployments" ]
    verbs: [ "list", "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: teamcity-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: teamcity-agent-rolebinding
subjects:
  - kind: ServiceAccount
    name: teamcity
